### PR TITLE
Add support for system colors.

### PR DESCRIPTION
**Pull request by jverkoey**
Closes https://github.com/mergesort/Recap/issues/7

Screenshots show the result of moving from static hex colors to system colors:

| Before | After |
|:---|:---|
| Simulator Screenshot - Trip analysis - 2024-10-15 at 10 23 45 | Simulator Screenshot - Trip analysis - 2024-10-15 at 10 23 21 |
| Simulator Screenshot - Trip analysis - 2024-10-15 at 10 23 43 | Simulator Screenshot - Trip analysis - 2024-10-15 at 10 23 23 |

### CODE REVIEW

**Comment by mergesort** [comment]
I made some updates to simplify the code a little bit by not introducing a new type, made some property naming updates, and updated the documentation a bit. What do you think @jverkoey?

**Review by electricsidecar-dev — APPROVED** [review]
lgtm!

**Comment by jverkoey** [comment]
gah, lgtm!

**Comment by jverkoey** [comment]
🥳🥳🥳🥳

**Pull request merged**
